### ISSUE TITLE
data for test

### ISSUE THREAD

**Issue by andorxornot** [zhshi0816/Video-Frame-Interpolation-Transformer#1]
can you add a small part of the dataset to the repository for the test inference?

**Comment by Tsubajashi** [comment]
you can just download Vimeo90K's Dataset. it may be helpful in the future no matter which AI you want to test.

**Comment by xuxy09** [comment]
> can you add a small part of the dataset to the repository for the test inference?

Hi, we use datasets suggested in [QVI](https://arxiv.org/abs/1911.00627) for evaluation, for example, the Davis dataset: https://www.dropbox.com/s/9t6x7fi9ui0x6bt/davis-90.zip?dl=0
