### ISSUE TITLE
Question about test result

### ISSUE THREAD

**Issue by SunInHeart** [zhshi0816/Video-Frame-Interpolation-Transformer#11]
Hi, Why my test PSNR is higher than yours when I test with your weight on Vimeo-90K?
Thanks.
![image](https://user-images.githubusercontent.com/63057663/206945076-fe40a909-6714-405e-ac3f-a8efef7e4925.png)
![image](https://user-images.githubusercontent.com/63057663/206945108-eb49c5c2-02ba-40a2-a868-d69211f9095b.png)

**Comment by zhshi0816** [comment]
I think you are testing on the 'mini' testset. You can switch to full testset by modifying ```vimeo90k_septuplet.py```.

**Comment by SunInHeart** [comment]
> I think you are testing on the 'mini' testset. You can switch to full testset by modifying `vimeo90k_septuplet.py`.

Thanks a lot.
