### ISSUE TITLE
Cupy version and installation

### ISSUE THREAD

**Issue by golddohyun** [zhshi0816/Video-Frame-Interpolation-Transformer#12]
I attempt to follow this excellent work and encounter some problems. I've tried to follow your initial settings of VFIT but i have a problem when installing cupy. Can you provide the details regarding the environment setup which is required to run the training code? (especially about the environment related to Cupy)

here's the pip packages that have been installed in my conda env
<img width="179" alt="image" src="https://user-images.githubusercontent.com/104754233/216804580-96c80e28-6284-45ac-aa8e-dd4316144859.png">

And the error is pasted as below.

`error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'wheel_includes': [], 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False, 'use_hip': False}
      
      -------- Configuring Module: cuda --------
      cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      /tmp/tmpcbr9cgg1/a.cpp:1:10: fatal error: cublas_v2.h: No such file or directory
       #include <cublas_v2.h>
                ^~~~~~~~~~~~~
      compilation terminated.
      command '/opt/ohpc/pub/compiler/gcc/7.3.0/bin/gcc' failed with exit code 1
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6yjw05j0/cupy_fca930965bbe445a80ec351ea4bb0674/setup.py", line 129, in <module>
          ext_modules = cupy_setup_build.get_ext_modules()
        File "/tmp/pip-install-6yjw05j0/cupy_fca930965bbe445a80ec351ea4bb0674/cupy_setup_build.py", line 744, in get_ext_modules
          extensions = make_extensions(arg_options, compiler, use_cython)
        File "/tmp/pip-install-6yjw05j0/cupy_fca930965bbe445a80ec351ea4bb0674/cupy_setup_build.py", line 492, in make_extensions
          raise Exception('Your CUDA environment is invalid. '
      Exception: Your CUDA environment is invalid. Please check above error log.`

**Comment by zhshi0816** [comment]
Hi, cupy is only compatible with pytorch-gpu version. it seems your cuda environment is invalid. Please check whether your cuda env is ok or not.

**Comment by golddohyun** [comment]
After proceeding with the cuad load, I proceeded with the installation again, and it worked well. Thank you.
