### ISSUE TITLE
different motion conditions of spliting the Vimeo dataset

### ISSUE THREAD

**Issue by Amazingren** [zhshi0816/Video-Frame-Interpolation-Transformer#15]
Hey @zhshi0816 @xuxy09 

Thanks for your insightful work on the video frame interpolation. I am interested in how to splite the Vimeo into fast/medium/slow sub-set? Can  you share me some idea on this ?

Bests regards,

**Comment by zhshi0816** [comment]
You can find here: https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/tree/master/datasets/meta_info

**Comment by Amazingren** [comment]
> You can find here: https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/tree/master/datasets/meta_info

Thanks a lot. I got it!

Bests
