### ISSUE TITLE
Low performance at UCF101 w/o crop

### ISSUE THREAD

**Issue by jzyustc** [zhshi0816/Video-Frame-Interpolation-Transformer#2]
Thanks for your great work! 

I found in the code images are cropped to (224, 224) for testing in UCF101, and in this case I get PSNR=33.44dB as reported.

However, the raw resolution of UCF101 is (225, 225), and when I remove thee cropping operation, the PSNR drops to 29.67dB. I am wondering how it happens. Does it mean VFIT is not robust to slight resolution change?

**Comment by xuxy09** [comment]
Thanks for your interest in our work. As the VFIT is based on non-overlapped window partition of the image, it is recommended to make the image size divisible by the window size (ie 8 here). However, it may not be proper to say "VFIT is not robust to slight resolution change", e.g., the network should be able to work well with (216, 216) or (208, 208), etc.

**Comment by xuxy09** [comment]
While the one-pixel crop does not seem to be a serious issue here, I would suggest two simple ways to circumvent this issue if you still prefer to work with (225, 225): 1) run VFIT for another 3 times by moving the cropped region by one pixel towards the down, right, and down-right sides, finally take the masked mean of the 4 results; 2) retrain the VFIT by considering random crop during the training process.

**Comment by jzyustc** [comment]
Thanks for your quick reply! I pad images to (232, 232) and evaluate again, and get PSNR=33.36, which is the same as at (224, 224). My question is well soved.

**Comment by xuxy09** [comment]
Good to know the issue is addressed. Just a quick note that reflection or replication padding may possibly give better results than zero padding (I haven't tried this though).
