### ISSUE TITLE
Is there a way to run this on pytorch 1.6 or higher?

### ISSUE THREAD

**Issue by issakh** [zhshi0816/Video-Frame-Interpolation-Transformer#3]
Hi, I am interesting in implementing your work, however, my GPU doesn't support cuda<11. So whenever torch=1.5.1 (or any version that doesn't support cuda 11) is installed, I get an error that cudnn could not find a convolution operation. This is expected as the GPU is not compatible with old cudnn and cuda versions.
With the provided code, it runs, but the performance of the model is static at around 15db. I have also tested this with the FLAVR code template (which is used here with modifications) and also the same issue.
I tried using code that I know works on newer torch versions and then changed the dataloader to the septuplet one you use, however, training is still broken.

Any ideas on how to solve this as would love to experiment with this network

Thanks

**Comment by xuxy09** [comment]
This seems to be an issue of PyTorch. I would suggest you ask the PyTorch team for help. By the way, if this problem is due to cudnn, one remedy I can think of is to turn cudnn off though it may affect the running speed.

**Comment by issakh** [comment]
Hi, I asked the pytorch team around a month ago (made a forum post) but they were unfortunately unable to help. I have tried turning off cudnn, but the speed is very slow. What's really difficult is determining exactly where the bug is and when looking at the code line by line, the functions used aren't depreciated

**Comment by junan146** [comment]
Hi, did you find where is the problem? I'm also looking for the problem, but couldn't find it.
