### ISSUE TITLE
About PSNR results in Table 1

### ISSUE THREAD

**Issue by rptxk01** [zhshi0816/Video-Frame-Interpolation-Transformer#4]
Thank you for sharing your impressive research.
The PSNR results listed in Table 1 of your paper are very different from those reported in other papers (even considering your retraining).
Papers such as DAIN, CAIN, RIFE, and XVFI show the same PSNR values for both the Vimeo90K and UCF101 datasets in their paper (presumably, they copied the values).
What is the reason for the large difference between the results reported in these papers?

**Comment by xuxy09** [comment]
Different from DAIN, RIFE, CAIN, and XVFI which use an input of 2 frames, we follow a more advanced setting of QVI and FLAVR where 4 input frames are used. As evidenced in [recent video interpolation challenges](https://arxiv.org/abs/2005.01233), this setting significantly improves the performance. 

To fit this setting, we use the UCF101 and Vimeo90K processed in QVI and FLAVR. That is to say, for example, the UCF101 in DAIN and QVI, are slightly different (triplets vs quintuples). Please check the original papers of QVI and FLAVR.
