### ISSUE TITLE
How to visualise the images generated by the model？

### ISSUE THREAD

**Issue by bojin-nwafu** [zhshi0816/Video-Frame-Interpolation-Transformer#5]
These are an exceptional work！Thank you for sharing！

**But I would like to know how to visualize the images generated by the model, like in Figures 5, 6 and 7 of the paper.**

I am very interested in this work and look forward to hearing from you!
Thanks!

**Comment by bojin-nwafu** [comment]
Looking forward to your response!

**Comment by xuxy09** [comment]
You can simply save the output image with OpenCV or other tools as JPEG or PNG.
