### ISSUE TITLE
Training epoch needed?

### ISSUE THREAD

**Issue by chautuankien** [zhshi0816/Video-Frame-Interpolation-Transformer#8]
I just found for paper on the internet and get interested in it. I have tried to execute your code, and got the result below
![8](https://user-images.githubusercontent.com/105159083/197095744-f25c08a9-f02f-4f5a-a1a5-4035756f74fb.png)

The results are getting worse after 10 epochs, so I wonder when you ran your code, how long did it take (how many epochs) for your model to converge? If you had the training log, could I have a look at it? Thank you.

**Comment by zhshi0816** [comment]
Hi,

Sorry, my training log is not handy. I trained the model for 100 epochs in total. I didn't notice the unconveragence problem.

What is your environment? Can you align the environment to us?

**Comment by chautuankien** [comment]
Sorry for replying late.

I use python 3.8, torch 1.10.1, cuda 11.3, cudnn 8.2.1, RTX 3090
I set batch size 8, ADAM, and trained from scratch with Vimeo-90K septuplets

**Comment by zhshi0816** [comment]
Can you try our enviroment? Thanks!

**Comment by zfbz** [comment]
I also failed in training.
![Snipaste_2022-11-15_15-35-46](https://user-images.githubusercontent.com/51376920/201857704-4c31cb3d-12e5-4ef6-a333-8cfd871da354.jpg)
But I successfully trained using the environment in README.md .
![Snipaste_2022-11-15_19-08-35](https://user-images.githubusercontent.com/51376920/201905283-9b6920cf-8cc8-4cbe-80f5-92af2421bee5.jpg)

**Comment by SunInHeart** [comment]
> I also failed in training. ![Snipaste_2022-11-15_15-35-46](https://user-images.githubusercontent.com/51376920/201857704-4c31cb3d-12e5-4ef6-a333-8cfd871da354.jpg) But I successfully trained using the environment in README.md . ![Snipaste_2022-11-15_19-08-35](https://user-images.githubusercontent.com/51376920/201905283-9b6920cf-8cc8-4cbe-80f5-92af2421bee5.jpg)

Hi, What type and how many gpus do you use in the second picture?
Thanks.

**Comment by zhshi0816** [comment]
2080Ti
