### ISSUE TITLE
question about the future frame rate after interpolation

### ISSUE THREAD

**Issue by hnsnsjkf** [zhshi0816/Video-Frame-Interpolation-Transformer#9]
The task of frame insertion is often to insert one or more frames between two frames. If my task is to change 30 frames to 60 frames, and if i insert one frame every two frames, there are only 59 frames. Where can I get the last frame? (I see some tasks 30fps-60fps or 120fps，but i do not understand how to make it by interpolation)

**Comment by zhshi0816** [comment]
Yes, you are right. We cannot synthesize the last frame, but that doesn't matter. A video usually last seconds, minutes, and hours, which contains tons of frames. We choose to omit the last frame by default.
